services:
  - type: web
    name: vics-royal-web
    runtime: docker
    plan: free
    envVars:
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: yourpassword
      # Add other environment variables here

  - type: worker
    name: vics-royal-celery-worker
    runtime: docker
    plan: free
    envVars:
      - fromGroup: vics-royal-web
    startCommand: celery -A vics_royal worker --loglevel=info --concurrency=2

  - type: worker
    name: vics-royal-celery-beat
    runtime: docker
    plan: free
    envVars:
      - fromGroup: vics-royal-web
    startCommand: celery -A vics_royal beat --loglevel=info