# Generated by Django 5.1.5 on 2025-07-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_available_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Enter sizes separated by commas. For hair extensions: 8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50 inches. For perfumes: 30ml,50ml,75ml,100ml,200ml. For shoes: 34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50', max_length=200, null=True),
        ),
    ]
