# Generated by Django 5.1.5 on 2025-07-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Enter sizes separated by commas. For hair extensions: 8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50 inches. For Other Products: 30ml,50ml,75ml,100ml,200ml.', max_length=200, null=True),
        ),
    ]
